'''
Created on Feb 27, 2016

@author: Pao
'''

PRESIDENT_CANDIDATES = ( (1, 'BINAY, JOJO (UNA)'),
                         (2, 'DEFENSOR SANTIAGO, MIRIAM (PRP)'),
                         (3, 'DUTERTE, RODY (PDPLBN)'),
                         (4, 'POE, GRACE (IND)'),
                         (5, 'ROXAS MAR (LP)'),
                         (6, 'SEÑERES, ROY (WPPPMM)'),
                         (7, 'ABSTAIN'),)

VP_CANDIDATES = ( (1, 'CAYETANO, ALAN PETER (IND)'),
                  (2, 'ESCUDERO, CHIZ (IND)'),
                  (3, 'HONASAN, GRINGO (UNA)'),
                  (4, 'MARCOS, BONGBONG (IND)'),
                  (5, 'ROBREDO, LENI (LP)'),
                  (6, 'TRILLANES, ANTONIO IV (IND)'),
                  (7, 'ABSTAIN'),)

SENATE_CANDIDATES_1 = ( (1,'ALBANI, SHARIFF (IND)'),
                        (2,'ALI, ALDIN (WPPPMM)'),
                        (3,'ALUNAN, RAFFY (IND)'),
                        (4,'AMBOLODTO, INA (LP)'),
                        (5,'ARQUIZA, GODOFREDO (IND)'),
                        (6,'BALIGOD, LEVITO (IND)'),
                        (7,'BELGICA, GRECO (IND)'),
                        (8,'BELLO, WALDEN (IND)'),
                        (9,'CAM, SANDRA (PMP)'),
                        (10,'CHAVEZ, MEL (WPPPMM)'),
                        (11,'COLMENARES, NERI (MKBYN)'),
                        (12, 'DELIMA, LEILA (LP)'),
                        (13, 'DOMAGOSO, ISKO MORENO (PMP)'),
                        (14,'DORONA, RAY (IND)'),
                        (15,'DRILON, FRANK (LP)'),
                        (16,'GADON, LARRY (KBL)'),
                        (17,'GATCHALIAN, WIN (NPC)'),
                        (18,'GORDON, DICK (LP)'),
                        (19,'GUINGONA, TG (LP)'),
                        (20,'HONTIVEROS, RISA (AKBYN)'),
                        (21,'KABALU, EID (IND)'),
                        (22,'KAPUNAN, LORNA (AKSYON)'),
                        (23,'KIRAM, PRONCESS JACEL (UNA)'),
                        (24,'LACSAMANA, ALMA MORENO (UNA)'),
                        (25,'LACSON, PANFILO (IND)'),)
                        
SENATE_CANDIDATES_2 =  ((26,'LANGIT, REY (UNA)'),
                        (27,'LAPID, MARK (AKSYON)'),
                        (28,'LIBAN, DANTE (IND)'),
                        (29,'MAGANTO, ROMEO (LAKAS)'),
                        (30,'MANZANO, EDU (IND)'),
                        (31,'MONTANO, ALLAN (UNA)'),
                        (32,'MONTAÑO, MON (IND)'),
                        (33,'NAPEÑAS, GETULIO (UNA)'),
                        (34,'OPLE, SUSAN (NP)'),
                        (35,'OSMEÑA, SERGIO III (IND)'),
                        (36,'PACQUIAO, MANNY (UNA)'),
                        (37,'PAEZ, MR. COOP (IND)'),
                        (38,'PAGDILAO, SAMUEL (IND)'),
                        (39,'PALPARAN, JOVITO JR. (IND)'),
                        (40,'PANGILINAN, KIKO (LP)'),
                        (41,'PETILLA, CARLOS JERICHO (LP)'),
                        (42,'RECTO, RALPH (LP)'),
                        (43,'ROMUALDEZ, MARTIN (LAKAS)'),
                        (44,'ROMULO, ROMAN (IND)'),
                        (45,'SANTIAGO, DIONISIO (IND)'),
                        (46,'SOTTO, VICENTE (NPC)'),
                        (47,'TOLENTINO, FRANCIS (IND)'),
                        (48,'VALEROSO. DIOSDADO (IND)'),
                        (49,'VILLANUEVA, JOEL (LP)'),
                        (50,'ZUBIRI, MIGZ (IND)'),)

SENATE_CANDIDATES   = ( (1,'ALBANI, SHARIFF (IND)'),
                        (2,'ALI, ALDIN (WPPPMM)'),
                        (3,'ALUNAN, RAFFY (IND)'),
                        (4,'AMBOLODTO, INA (LP)'),
                        (5,'ARQUIZA, GODOFREDO (IND)'),
                        (6,'BALIGOD, LEVITO (IND)'),
                        (7,'BELGICA, GRECO (IND)'),
                        (8,'BELLO, WALDEN (IND)'),
                        (9,'CAM, SANDRA (PMP)'),
                        (10,'CHAVEZ, MEL (WPPPMM)'),
                        (11,'COLMENARES, NERI (MKBYN)'),
                        (12, 'DELIMA, LEILA (LP)'),
                        (13, 'DOMAGOSO, ISKO MORENO (PMP)'),
                        (14,'DORONA, RAY (IND)'),
                        (15,'DRILON, FRANK (LP)'),
                        (16,'GADON, LARRY (KBL)'),
                        (17,'GATCHALIAN, WIN (NPC)'),
                        (18,'GORDON, DICK (LP)'),
                        (19,'GUINGONA, TG (LP)'),
                        (20,'HONTIVEROS, RISA (AKBYN)'),
                        (21,'KABALU, EID (IND)'),
                        (22,'KAPUNAN, LORNA (AKSYON)'),
                        (23,'KIRAM, PRONCESS JACEL (UNA)'),
                        (24,'LACSAMANA, ALMA MORENO (UNA)'),
                        (25,'LACSON, PANFILO (IND)'),
                        (26,'LANGIT, REY (UNA)'),
                        (27,'LAPID, MARK (AKSYON)'),
                        (28,'LIBAN, DANTE (IND)'),
                        (29,'MAGANTO, ROMEO (LAKAS)'),
                        (30,'MANZANO, EDU (IND)'),
                        (31,'MONTANO, ALLAN (UNA)'),
                        (32,'MONTAÑO, MON (IND)'),
                        (33,'NAPEÑAS, GETULIO (UNA)'),
                        (34,'OPLE, SUSAN (NP)'),
                        (35,'OSMEÑA, SERGIO III (IND)'),
                        (36,'PACQUIAO, MANNY (UNA)'),
                        (37,'PAEZ, MR. COOP (IND)'),
                        (38,'PAGDILAO, SAMUEL (IND)'),
                        (39,'PALPARAN, JOVITO JR. (IND)'),
                        (40,'PANGILINAN, KIKO (LP)'),
                        (41,'PETILLA, CARLOS JERICHO (LP)'),
                        (42,'RECTO, RALPH (LP)'),
                        (43,'ROMUALDEZ, MARTIN (LAKAS)'),
                        (44,'ROMULO, ROMAN (IND)'),
                        (45,'SANTIAGO, DIONISIO (IND)'),
                        (46,'SOTTO, VICENTE (NPC)'),
                        (47,'TOLENTINO, FRANCIS (IND)'),
                        (48,'VALEROSO. DIOSDADO (IND)'),
                        (49,'VILLANUEVA, JOEL (LP)'),
                        (50,'ZUBIRI, MIGZ (IND)'),)


PARTY_LIST_1 = ((1,'AGRI'),
            (2,'ASEAN, INC.'),
            (3,'METRO'),
            (4,'TRICAP'),
            (5,'ABANG LINGKOD'),
            (6,'DIWA'),
            (7,'AKIN'),
            (8,'AGAP'),
            (9,'SBP'),
            (10,'ADDA'),
            (11,'AWAT MINDANAO'),
            (12,'ANAKALUSUGAN'),
            (13,'CLASE'),
            (14,'AKBAYAN'),
            (15,'ALL-FISH'),
            (16,'AKO BICOL'),
            (17,'SINAG'),
            (18,'1-ABILIDAD'),
            (19,'GLOBAL'),
            (20,'1-ANG EDUKASYON'),
            (21,'COOP-NATCCO'),
            (22,'ALAY BUHAY'),
            (23,'ACP'),
            (24,'1-GB'),
            (25,'1PACMAN'),
            (26,'MELCHORA'),
            (27,'1-AHAPO'),
            (28,'TINGOG SINIRANGAN'),
            (29,'PBB'),)

PARTY_LIST_2 = ((30,'KABAYAN'),
            (31,'ACT TEACHERS'),
            (32,'ANG KABUHAYAN'),
            (33,'KMM'),
            (34,'YACAP'),
            (35,'TAMA'),
            (36,'GABRIELA'),
            (37,'SANLAKAS'),
            (38,'ABAKADA'),
            (39,'ABS'),
            (40,'LPGMA'),
            (41,'UNIDO'),
            (42,'KM NGAYON NA'),
            (43,'ANGKLA'),
            (44,'ALONA'),
            (45,'TGP'),
            (46,'MAGDALO'),
            (47,'OFWFC'),
            (48,'ALE'),
            (49,'ATING GURO'),
            (50,'AVE'),
            (51,'A TEACHER, INC.'),
            (52,'ANAKPAWIS'),
            (53,'RAM'),
            (54,'CWS'),
            (55,'KABATAAN'),
            (56,'PISTON'),
            (57,'TUCP'),
            (58,'KALINGA'),)

PARTY_LIST_3 =((59,'AASENSO'),
            (60,'AAMBIS-OWA'),
            (61,'AAB'),
            (62,'ABONO'),
            (63,'AMIN'),
            (64,'AGHAM'),
            (65,'ANUPA'),
            (66,'DISABLED/PWD'),
            (67,'TINDERONG PINOY'),
            (68,'CONSLA'),
            (69,'SENIOR CITIZENS'),
            (70,'MIGRANTE'),
            (71,'AMOR-SEAMAN'),
            (72,'CIBAC'),
            (73,'NACTODAP'),
            (74,'A TAMBAY'),
            (75,'BANAT'),
            (76,'UMALAB KA'),
            (77,'A.I.'),
            (78,'AN WARAY'),
            (79,'KUSUG TAUSUG'),
            (80,'ANG NARS'),
            (81,'BAYAN MUNA'),
            (82,'MARINO'),
            (83,'ANG KASANGGA'),
            (84,'AMA'),
            (85,'KAP/KAKASA-KA'),
            (86,'FICTAP'),
            (87,'SAMAKO'),)
PARTY_LIST_4 =((88,'ACTS-OFW'),
            (89,'PBA'),
            (90,'MANILA TEACHERS'),
            (91,'ANAC-IP'),
            (92,'ABANTE RETIREES'),
            (93,'BUTIL'),
            (94,'KAMAIS PILIPINAS'),
            (95,'ATING KOOP'),
            (96,'ACT-CIS'),
            (97,'1-CARE'),
            (98,'MATA'),
            (99,'DUMPER PTDA'),
            (100,'BH'),
            (101,'PM'),
            (102,'1-SAGIP'),
            (103,'1-PABAHAY'),
            (104,'CANCER'),
            (105,'MTM PHILS'),
            (106,'1-AALALAY'),
            (107,'AANGAT TAYO'),
            (108,'ABAMIN'),
            (109,'ANG PROLIFE'),
            (110,'BUHAY'),
            (111,'APPEND'),
            (112,'KGB'),
            (113,'AGBIAG!'),
            (114,'AWAKE'),
            (115,'AMEPA OFW'),)

PARTY_LIST = ((1,'AGRI'),
            (2,'ASEAN, INC.'),
            (3,'METRO'),
            (4,'TRICAP'),
            (5,'ABANG LINGKOD'),
            (6,'DIWA'),
            (7,'AKIN'),
            (8,'AGAP'),
            (9,'SBP'),
            (10,'ADDA'),
            (11,'AWAT MINDANAO'),
            (12,'ANAKALUSUGAN'),
            (13,'CLASE'),
            (14,'AKBAYAN'),
            (15,'ALL-FISH'),
            (16,'AKO BICOL'),
            (17,'SINAG'),
            (18,'1-ABILIDAD'),
            (19,'GLOBAL'),
            (20,'1-ANG EDUKASYON'),
            (21,'COOP-NATCCO'),
            (22,'ALAY BUHAY'),
            (23,'ACP'),
            (24,'1-GB'),
            (25,'1PACMAN'),
            (26,'MELCHORA'),
            (27,'1-AHAPO'),
            (28,'TINGOG SINIRANGAN'),
            (29,'PBB'),
            (30,'KABAYAN'),
            (31,'ACT TEACHERS'),
            (32,'ANG KABUHAYAN'),
            (33,'KMM'),
            (34,'YACAP'),
            (35,'TAMA'),
            (36,'GABRIELA'),
            (37,'SANLAKAS'),
            (38,'ABAKADA'),
            (39,'ABS'),
            (40,'LPGMA'),
            (41,'UNIDO'),
            (42,'KM NGAYON NA'),
            (43,'ANGKLA'),
            (44,'ALONA'),
            (45,'TGP'),
            (46,'MAGDALO'),
            (47,'OFWFC'),
            (48,'ALE'),
            (49,'ATING GURO'),
            (50,'AVE'),
            (51,'A TEACHER, INC.'),
            (52,'ANAKPAWIS'),
            (53,'RAM'),
            (54,'CWS'),
            (55,'KABATAAN'),
            (56,'PISTON'),
            (57,'TUCP'),
            (58,'KALINGA'),
            (59,'AASENSO'),
            (60,'AAMBIS-OWA'),
            (61,'AAB'),
            (62,'ABONO'),
            (63,'AMIN'),
            (64,'AGHAM'),
            (65,'ANUPA'),
            (66,'DISABLED/PWD'),
            (67,'TINDERONG PINOY'),
            (68,'CONSLA'),
            (69,'SENIOR CITIZENS'),
            (70,'MIGRANTE'),
            (71,'AMOR-SEAMAN'),
            (72,'CIBAC'),
            (73,'NACTODAP'),
            (74,'A TAMBAY'),
            (75,'BANAT'),
            (76,'UMALAB KA'),
            (77,'A.I.'),
            (78,'AN WARAY'),
            (79,'KUSUG TAUSUG'),
            (80,'ANG NARS'),
            (81,'BAYAN MUNA'),
            (82,'MARINO'),
            (83,'ANG KASANGGA'),
            (84,'AMA'),
            (85,'KAP/KAKASA-KA'),
            (86,'FICTAP'),
            (87,'SAMAKO'),
            (88,'ACTS-OFW'),
            (89,'PBA'),
            (90,'MANILA TEACHERS'),
            (91,'ANAC-IP'),
            (92,'ABANTE RETIREES'),
            (93,'BUTIL'),
            (94,'KAMAIS PILIPINAS'),
            (95,'ATING KOOP'),
            (96,'ACT-CIS'),
            (97,'1-CARE'),
            (98,'MATA'),
            (99,'DUMPER PTDA'),
            (100,'BH'),
            (101,'PM'),
            (102,'1-SAGIP'),
            (103,'1-PABAHAY'),
            (104,'CANCER'),
            (105,'MTM PHILS'),
            (106,'1-AALALAY'),
            (107,'AANGAT TAYO'),
            (108,'ABAMIN'),
            (109,'ANG PROLIFE'),
            (110,'BUHAY'),
            (111,'APPEND'),
            (112,'KGB'),
            (113,'AGBIAG!'),
            (114,'AWAKE'),
            (115,'AMEPA OFW'),)
