'''
Created on Feb 27, 2016

@author: Pao
'''

PRESIDENT_CANDIDATES = ( (1, 'Jejomar Binay'),
                         (2, 'Miriam Defensor Santiago'),
                         (3, 'Rodrigo Duterte'),
                         (4, 'Grace Poe'),
                         (5, 'Mar Roxas'),
                         (6, 'Abstain'),)

VP_CANDIDATES = ( (1, 'Alan Peter Cayetano'),
                  (2, 'Francis Escudero'),
                  (3, 'Gregorio Honasan'),
                  (4, 'Ferdinand Marcos Jr.'),
                  (5, 'Leni Robredo'),
                  (6, 'Antonio Trillanes'),
                  (7, 'Abstain'),)

SENATE_CANDIDATES_1 = ( (1,'Risa Hontiveros'),
                        (2,'Lorna Kapunan'),
                        (3,'Mark Lapid'),
                        (4,'Larry Gadon'),
                        (5,'Romeo Maganto'),
                        (6,'Martin Romualdez'),
                        (7,'Ina Ambolodto'),
                        (8,'Leila de Lima'),
                        (9,'Franklin Drilon'),
                        (10,'TG Guingona'),
                        (11,'Francis Pangilinan'),
                        (12,'Jericho Petilla'),
                        (13,'Ralph Recto'),
                        (14,'Joel Villanueva'),
                        (15,'Neri Colmenares'),
                        (16,'Princess Jacel Kiram'),
                        (17,'Alma Moreno'),
                        (18,'Rey Langit'),
                        (19,'Allan Montano'),
                        (20,'Getulio Napeñas'),
                        (21,'Manny Pacquiao'),
                        (22,'Sandra Cam'),
                        (23,'Isko Moreno'),
                        (24,'Aldin Ali'),
                        (25,'Melchor Chavez'),)
                        
SENATE_CANDIDATES_2 =  ((26,'Sherwin Gatchalian'),
                        (27,'Tito Sotto'),
                        (28,'Susan Ople'),
                        (29,'Shariff Albani'),
                        (30,'Rafael Alunan'),
                        (31,'Godofredo Arquiza'),
                        (32,'Levito Baligod'),
                        (33,'Greco Belgica'),
                        (34,'Walden Bello'),
                        (35,'Ray Dorona'),
                        (36,'Richard J. Gordon'),
                        (37,'Eid Kabalu'),
                        (38,'Panfilo Lacson'),
                        (39,'Dante Liban'),
                        (40,'Edu Manzano'),
                        (41,'Ramon Montaño'),
                        (42,'Sergio Osmeña III'),
                        (43,'Cresente Paez'),
                        (44,'Samuel Pagdilao'),
                        (45,'Jovito Palparan'),
                        (46,'Roman Romulo'),
                        (47,'Dionisio Santiago'),
                        (48,'Francis Tolentino'),
                        (49,'Diosdado Valeroso'),
                        (50,'Juan Miguel Zubiri'),
                        (51, 'Abstain'),)
